// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mobile/Login.tsx": () => import("../components/mockups/mobile/Login.tsx"),
  "./components/mockups/mobile/Modules.tsx": () => import("../components/mockups/mobile/Modules.tsx"),
  "./components/mockups/mobile/Paywall.tsx": () => import("../components/mockups/mobile/Paywall.tsx"),
  "./components/mockups/mobile/Terminal.tsx": () => import("../components/mockups/mobile/Terminal.tsx")
};
